services:
  python-app:
    build:
      context: .
    container_name: python-app
    restart: unless-stopped
    init: true
    env_file: ./.env  
    ports:
      - "8000:8000"  # Exposes Django development server
    depends_on:
      - postgres
    networks:
      - backend
    develop:
      watch:
        - path: .
          action: sync 
          target: /app

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pgdata:
    # Persistent storage for PostgreSQL
